server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: data
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:5432/store
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: data
  jpa:
    properties:
      hibernate:
        default_schema: data
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json # ajuste para o endpoint JWKS do seu autorizador/gateway

logging:
  level:
    espm: ${LOGGING_LEVEL_ESPM:debug}